import type { JobResponse } from "../../apps/web/src/lib/types";

export function createMockJob(
  overrides: Partial<JobResponse> = {},
  clipOverrides: Array<Partial<JobResponse["clips"][number]>> = []
): JobResponse {
  const clips = [
    {
      id: "clip-1",
      text: "Keep the labeling steady across every segment.",
      start: 2,
      end: 4.2,
      duration: 2.2,
      confidence: 0.93,
      speech_rate: 2.7,
      energy: 0.82,
      silence_ratio: 0.08,
      instability: 0.12,
      score: 91,
      quality_label: "Excellent" as const,
      explanation: "High confidence, clear signal, and stable delivery.",
      source_video_id: "video-1",
      playback: {
        url: "/api/jobs/demo-job/video",
        start: 2,
        end: 4.2,
      },
      audio_features: {
        volume: { value: 0.82, normalized: 0.82 },
        speech_rate: { value: 2.7, normalized: 0.67 },
        snr: { value: 0.84, normalized: 0.84 },
        spectral: {
          centroid_hz: { value: 1900, normalized: 0.53 },
          bandwidth_hz: { value: 1260, normalized: 0.45 },
          rolloff_hz: { value: 3380, normalized: 0.61 },
          flatness: { value: 0.14, normalized: 0.14 },
          zero_crossing_rate: { value: 0.05, normalized: 0.05 },
        },
      },
      linguistic_features: {
        word_count: 7,
        lexical_diversity: 0.92,
        filler_word_count: 0,
        filler_words: [],
        pos_distribution: { noun: 0.28, verb: 0.22 },
      },
      word_alignments: [
        { token: "Keep", start: 2, end: 2.25, confidence: 0.96 },
        { token: "segment.", start: 3.82, end: 4.2, confidence: 0.91 },
      ],
      visual_features: {
        sampled_frame_count: 14,
        face_detection: { value: 0.96, normalized: 0.96 },
        mouth_movement: { value: 0.79, normalized: 0.79 },
        visibility: { value: 0.93, normalized: 0.93 },
      },
      quality_breakdown: {
        transcription_confidence: 0.93,
        pacing: 0.76,
        acoustic_signal: 0.84,
        continuity: 0.9,
        stability: 0.84,
        linguistic_clarity: 0.75,
        visual_readiness: 0.8,
        boundary_cleanliness: 0.92,
        speech_density: 0.83,
        dedupe_confidence: 0.98,
        overall: 0.91,
      },
      quality_reasoning: {
        summary: "Stable and training-ready.",
        strengths: ["High confidence", "Clean signal"],
        cautions: [],
      },
      candidate_metrics: {
        pause_count: 0,
        max_gap_seconds: 0.08,
        speech_density: 0.83,
        low_confidence_ratio: 0,
        leading_filler_ratio: 0,
        trailing_filler_ratio: 0,
        boundary_punctuation_strength: 1,
      },
      selection_recommendation: "shortlist" as const,
      quality_penalties: [],
      tags: ["training-ready", "clear-speech", "boundary-clean", "av-ready"],
      recommended_use: ["speech-annotation", "av-ready"],
      embedding_vector: null,
    },
    {
      id: "clip-2",
      text: "Add more context before the final label.",
      start: 8,
      end: 10.6,
      duration: 2.6,
      confidence: 0.82,
      speech_rate: 2.2,
      energy: 0.68,
      silence_ratio: 0.15,
      instability: 0.21,
      score: 73,
      quality_label: "Good" as const,
      explanation: "Good confidence with slightly softer delivery.",
      source_video_id: "video-1",
      playback: {
        url: "/api/jobs/demo-job/video",
        start: 8,
        end: 10.6,
      },
      audio_features: {
        volume: { value: 0.68, normalized: 0.68 },
        speech_rate: { value: 2.2, normalized: 0.55 },
        snr: { value: 0.7, normalized: 0.7 },
        spectral: {
          centroid_hz: { value: 1760, normalized: 0.49 },
          bandwidth_hz: { value: 1180, normalized: 0.41 },
          rolloff_hz: { value: 3200, normalized: 0.57 },
          flatness: { value: 0.17, normalized: 0.17 },
          zero_crossing_rate: { value: 0.07, normalized: 0.07 },
        },
      },
      linguistic_features: {
        word_count: 8,
        lexical_diversity: 0.88,
        filler_word_count: 0,
        filler_words: [],
        pos_distribution: { noun: 0.24, verb: 0.21 },
      },
      word_alignments: [
        { token: "Add", start: 8, end: 8.22, confidence: 0.91 },
        { token: "label.", start: 10.2, end: 10.6, confidence: 0.87 },
      ],
      visual_features: {
        sampled_frame_count: 14,
        face_detection: { value: 0.89, normalized: 0.89 },
        mouth_movement: { value: 0.66, normalized: 0.66 },
        visibility: { value: 0.87, normalized: 0.87 },
      },
      quality_breakdown: {
        transcription_confidence: 0.82,
        pacing: 0.68,
        acoustic_signal: 0.69,
        continuity: 0.81,
        stability: 0.72,
        linguistic_clarity: 0.73,
        visual_readiness: 0.71,
        boundary_cleanliness: 0.58,
        speech_density: 0.69,
        dedupe_confidence: 0.81,
        overall: 0.73,
      },
      quality_reasoning: {
        summary: "Useful, but less decisive than the top clip.",
        strengths: ["Balanced pacing"],
        cautions: ["Softer signal"],
      },
      candidate_metrics: {
        pause_count: 1,
        max_gap_seconds: 0.26,
        speech_density: 0.69,
        low_confidence_ratio: 0.12,
        leading_filler_ratio: 0,
        trailing_filler_ratio: 0,
        boundary_punctuation_strength: 0.5,
      },
      selection_recommendation: "review" as const,
      quality_penalties: ["boundary_messy"],
      tags: ["contextual", "review-needed"],
      recommended_use: ["review"],
      embedding_vector: null,
    },
  ].map((clip, index) => ({ ...clip, ...(clipOverrides[index] ?? {}) }));

  return {
    jobId: "demo-job",
    status: "ready",
    progressPhase: "ready",
    error: null,
    sourceVideo: {
      id: "video-1",
      file_name: "demo-session.mp4",
      content_type: "video/mp4",
      size_bytes: 19_500_000,
      duration_seconds: 180,
      url: "/api/jobs/demo-job/video",
    },
    summary: {
      duration_seconds: 180,
      transcript_preview: "Keep the labeling steady across every segment.",
      clip_count: clips.length,
      excellent_count: 1,
      good_count: 1,
      weak_count: 0,
      average_score: 82,
      top_score: 91,
      shortlist_recommended_count: 1,
    },
    clips,
    timeline: [
      { start: 0, end: 15, score: 38, quality_label: "Weak", top_clip_id: null },
      { start: 15, end: 30, score: 91, quality_label: "Excellent", top_clip_id: "clip-1" },
      { start: 30, end: 45, score: 73, quality_label: "Good", top_clip_id: "clip-2" },
      { start: 45, end: 60, score: 42, quality_label: "Weak", top_clip_id: null },
    ],
    language: "en",
    processingTimings: {
      extracting_audio: 1.2,
      transcribing: 7.5,
      segmenting: 0.7,
      scoring: 0.4,
      total: 9.8,
    },
    warnings: [],
    processingStats: {
      source_duration_seconds: 180,
      transcript_word_count: 320,
      candidate_clip_count: 24,
      discarded_candidate_count: 5,
      deduped_candidate_count: 3,
      shortlist_recommended_count: 1,
      clip_count: clips.length,
      timeline_bin_count: 48,
    },
    createdAt: "2026-04-01T12:00:00.000Z",
    updatedAt: "2026-04-01T12:10:00.000Z",
    ...overrides,
  };
}
